services:
  BWCMS.Admin:
      class: Bellwether\BWCMSBundle\Classes\Service\AdminService
      arguments: ["@knp_menu.factory",@service_container,@request_stack]
  BWCMS.ACL:
    class: Bellwether\BWCMSBundle\Classes\Service\ACLService
    arguments: [@service_container,@request_stack]
  BWCMS.Cache:
    class: Bellwether\BWCMSBundle\Classes\Service\CacheService
    arguments: [@service_container,@request_stack]
  BWCMS.Site:
    class: Bellwether\BWCMSBundle\Classes\Service\SiteService
    arguments: [@service_container,@request_stack]
  BWCMS.Preference:
    class: Bellwether\BWCMSBundle\Classes\Service\PreferenceService
    arguments: [@service_container,@request_stack]
  BWCMS.Content:
    class: Bellwether\BWCMSBundle\Classes\Service\ContentService
    arguments: [@service_container,@request_stack]
  BWCMS.ContentQuery:
    class: Bellwether\BWCMSBundle\Classes\Service\ContentQueryService
    arguments: [@service_container,@request_stack]
  BWCMS.Search:
    class: Bellwether\BWCMSBundle\Classes\Service\SearchService
    arguments: [@service_container,@request_stack]
  BWCMS.Locale:
    class: Bellwether\BWCMSBundle\Classes\Service\LocaleService
    arguments: [@service_container,@request_stack]
  BWCMS.Media:
    class: Bellwether\BWCMSBundle\Classes\Service\MediaService
    arguments: [@service_container,@request_stack]
  BWCMS.Mailer:
    class: Bellwether\BWCMSBundle\Classes\Service\MailService
    arguments: [@service_container,@request_stack]
  BWCMS.Template:
     class: Bellwether\BWCMSBundle\Classes\Service\TemplateService
     arguments: [@service_container,@request_stack]
  BWCMS.Router:
    class: Bellwether\BWCMSBundle\Classes\Service\RoutingService
    arguments: [@service_container,@request_stack]
    tags:
      - { name: routing.loader }
  BWCMS.Twig.Extension:
    class: Bellwether\BWCMSBundle\Classes\Service\TwigService
    arguments: ["@knp_menu.factory",@service_container,@request_stack]
    public: false
    tags:
      - { name: twig.extension }
  BWCMS.Form.Type.Content:
    class: Bellwether\BWCMSBundle\Form\Type\ContentType
    arguments: [@service_container]
    tags:
      - { name: form.type , alias: bwcms_content }
  BWCMS.Form.Type.Content.Template:
    class: Bellwether\BWCMSBundle\Form\Type\ContentTemplateType
    arguments: [@service_container]
    tags:
      - { name: form.type , alias: bwcms_content_template }
  BWCMS.Form.Type.Taxonomy.Tree:
    class: Bellwether\BWCMSBundle\Form\Type\TaxonomyTreeType
    arguments: [@service_container]
    tags:
      - { name: form.type , alias: bwcms_taxonomy_tree }
  BWCMS.Form.Type.Collection:
    class: Bellwether\BWCMSBundle\Form\Type\CollectionType
    tags:
      - { name: form.type , alias: bwcms_collection }
  BWCMS.Admin.LeftMenu:
      class: Knp\Menu\MenuItem
      factory_service: BWCMS.Admin
      factory_method: buildLeftMainMenu
      arguments: ["@request"]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: Admin.LeftMenu }
  BWCMS.Admin.RightMenu:
      class: Knp\Menu\MenuItem
      factory_service: BWCMS.Admin
      factory_method: buildRightMainMenu
      arguments: ["@request"]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: Admin.RightMenu }
  BWCMS.KernelEventListener:
        class: Bellwether\BWCMSBundle\EventListener\KernelEventListener
        arguments: [@kernel,@service_container,@request_stack]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
            - { name: kernel.event_listener, event: security.kernel_response, method: onSecurityException }
